name: Build Library

on:
  push
  
jobs:

  Build-Library:
    name: Build library
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Build Bme680 project
        run: dotnet build --configuration Release src/
